### ISSUE TITLE
按照文档说明构建失败，缺少tinyid-base:jar:0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by menng** [didi/tinyid#1]
执行`sh build.sh offline`报错：
`Failed to collect dependencies at com.xiaoju.uemc.tinyid:tinyid-base:jar:0.1.0-SNAPSHOT`  
是否要新增先构建`tinyid-base`的脚本？

**Comment by duimba** [comment]
fixed, 3ks 
已经修复了~多谢反馈!
