### ISSUE TITLE
有个非常严重的Bug

### ISSUE THREAD

**Issue by westonlv** [didi/tinyid#10]
在动态数据源DynamicDataSource类中determineCurrentLookupKey，每次都是随机选择真实的DataSource，但是在DbSegmentIdServiceImpl.getNextSegmentId方法中使用了乐观锁，每获取一个SegmentInfo都存在query 以及 update 数据的动作，所以query和update可能操作的不是同一张表

**Comment by duimba** [comment]
这的确是一个严重的bug......
已经修复，通过在DbSegmentIdServiceImpl.getNextSegmentId方法上增加了@Transactional标记，保证了同一connection
同时修改了dao层的update方法，增加了biz_type判定,以防意外

**Comment by duimba** [comment]
> 在动态数据源DynamicDataSource类中determineCurrentLookupKey，每次都是随机选择真实的DataSource，但是在DbSegmentIdServiceImpl.getNextSegmentId方法中使用了乐观锁，每获取一个SegmentInfo都存在query 以及 update 数据的动作，所以query和update可能操作的不是同一张表

这的确是一个严重的bug......
已经修复，通过在DbSegmentIdServiceImpl.getNextSegmentId方法上增加了@transactional标记，保证了同一connection
同时修改了dao层的update方法，增加了biz_type判定,以防意外
