### ISSUE TITLE
DbSegmentIdServiceImpl的retry全局变量

### ISSUE THREAD

**Issue by zhaoche27** [didi/tinyid#5]
单例的DbSegmentIdServiceImpl的retry全局变量，最好搞成常量，大写。

IdController 中 idGeneratorFactoryServer.getIdGenerator(bizType)  每次返回的都是新的CachedIdGenerator的实例，而你在这个实例里搞了（实例）锁，起不到对数据库（version冲突）减压的效果。应该锁 “bizType”

**Comment by duimba** [comment]
retry命名确实不规范
每个bizType实际内存只有一个CachedIdGenerator实例，有个cache，如果cache中有，不会create了 @zhaoche27

**Comment by zhaoche27** [comment]
![image](https://user-images.githubusercontent.com/5029131/52856600-d95e4980-315f-11e9-8859-8d7a64da982f.png)

**Comment by zhaoche27** [comment]
![image](https://user-images.githubusercontent.com/5029131/52857086-1414b180-3161-11e9-86f9-f00d483a7433.png)

**Comment by duimba** [comment]
这个地方是多此一举了
